### ISSUE TITLE
Optimize big picture

### ISSUE THREAD

**Issue by MaxSemenchuk** [vacekj/regenscore#103]

**Comment by MaxSemenchuk** [comment]
The big leaf picture is loading quite long time, maybe needs optimization 

![Image](https://github.com/vacekj/regenscore/assets/11428528/1d11a20a-1207-45ea-a8db-af12f4948f4a)

**Comment by vacekj** [comment]
@b3nik
1. convert the image to webp locally
2. crop/change the dimensions to the largest possible display dimensions
3. if still slow (over 500kB), use `next/image`

for comparison, take a lighthouse perf. report of the landing page after each step.

**Comment by vacekj** [comment]
closed by #113
