### ISSUE TITLE
Score shows even on the wrong network

### ISSUE THREAD

**Issue by iviangita** [vacekj/regenscore#106]
It still shows my score in this tiny corner when I'm on a different network - can we remove it? 

<img width="850" alt="image" src="https://github.com/vacekj/regenscore/assets/74632674/0f7c9ad4-6a6b-46bf-a874-31be397158b5">

**Comment by vacekj** [comment]
The score calculation is independent of the connected wallet chain - the user only needs to be on the correct chain when paying for the attestation, which is handled already.
