### ISSUE TITLE
Minor markup improvements

### ISSUE THREAD

**Issue by Tosinolawale** [vacekj/regenscore#12]
![1](https://github.com/vacekj/regenscore/assets/35389241/62f91b4f-bf6f-40e5-abac-0c8cc154efee)
Should be on a single line, no line breaks 

![2](https://github.com/vacekj/regenscore/assets/35389241/900c57c3-c1d2-4368-a7ac-ec8e57c2180e)
Should also be on a single line, no lines breaks on "Improve your regen score" heading 

![3](https://github.com/vacekj/regenscore/assets/35389241/714d9c05-99e1-4feb-8eec-6f791bd4c903)
H2 heading and text boxes should be aligned with the header image

**Comment by Tosinolawale** [comment]
@mateodaza

**Comment by Tosinolawale** [comment]
![4](https://github.com/vacekj/regenscore/assets/35389241/c40dfaae-a988-4fef-92af-d5aed7c20384)
No Padding on the responsive screen sizes

![5](https://github.com/vacekj/regenscore/assets/35389241/299ad9d6-0b1f-4cac-be39-0710d17c6680)
the text boxes are not vertically aligned on the various responsive screens 

![6](https://github.com/vacekj/regenscore/assets/35389241/542ed2cb-3694-4a40-b3dd-5b98eb11bd44)
update new logo on the footer

**Comment by MaxSemenchuk** [comment]
Use inter font here

<img width="327" alt="image" src="https://github.com/vacekj/regenscore/assets/11428528/59842b11-d593-4956-9fc6-ca529716a1e1">

**Comment by MaxSemenchuk** [comment]
Use inter font here wansn't solved @b3nik
