### ISSUE TITLE
Have not received attestation

### ISSUE THREAD

**Issue by 0x398** [vacekj/regenscore#121]
Hi,

I've sent attestation request, but have not received attestation.
https://optimistic.etherscan.io/tx/[redacted]
Looks like watchdog for 0xd8dA8766431366E9aD63eA6D16d9199cece2aA08 is down.

**Comment by mateodaza** [comment]
@0x398 can you try minting again please? you won't be charged twice

**Comment by 0x398** [comment]
@mateodaza I've just tried it and when I click "mint attestation" on https://regenscore.io/profile it just offers to send ETH again.

**Comment by 0x398** [comment]
@b3nik @mateodaza Any updates?

**Comment by vacekj** [comment]
Hey - I'll check again and manually mint your attestation if present. Sorry for the wait, and thank you for your patience.

**Comment by 0x398** [comment]
@vacekj still waiting for this ...

**Comment by vacekj** [comment]
@0x398 Apologies for the delay - I've queued a refund transaction for you.

**Comment by 0x398** [comment]
@vacekj I have not asked for refund, you can keep it. I asked for an attestation. You guys such a joke. Requested tons of OP and failed to deliver even MVP.

**Comment by vacekj** [comment]
> @vacekj I have not asked for refund, you can keep it. I asked for an attestation. You guys such a joke. Requested tons of OP and failed to deliver even MVP.

The refund has already been processed. 

As for the project - we have delivered on all of our original milestones as outlined in the grant application. We will have an announcement about the future of the project soon.
