### ISSUE TITLE
Attestation doesn't reflect on the schema page

### ISSUE THREAD

**Issue by iviangita** [vacekj/regenscore#134]
I re-minted my Regen Score and $1 was deducted from my wallet, but it doesn't reflect on the Schema page 🤔

See my transaction here: https://optimistic.etherscan.io/tx/0xca698d6849541dfe29b94bbd130ba824f75edcfe169bf24a4466282db9e34be2

Last attestation was 2 months ago 

<img width="926" alt="image" src="https://github.com/vacekj/regenscore/assets/74632674/d23f41dc-b5f5-4839-90a0-320be5e952f3">

**Comment by 0x398** [comment]
This project is scam. They just applying for grants, but do not ship anything remotely working and just keep giving useless responses once in few month. See my very similar issue https://github.com/vacekj/regenscore/issues/121

**Comment by vacekj** [comment]
@0x398 I'm sorry to hear you're feeling this way. I can assure you we have delivered on all our grant milestones on schedule.

Regenscore is currently under maintenance and all services are paused until further notice. We will share more information about the future of the project soon. Thank you for your patience.
