### ISSUE TITLE
Move to Multisig

### ISSUE THREAD

**Issue by vacekj** [vacekj/regenscore#2]
- [ ] Setup a 2 out of 3 Gnosis Safe on Mainnet
- [ ] Move 100 USDC from EthNYC to Multisig
- [ ] Swap FIL grant to USDC and move to Multisig
- [ ] Move ENS to Multisig

@mopdo @ccerv1 would you agree to be on the Multisig?

**Comment by mopdo** [comment]
Sounds good! We might need to switch up @ccerv1 with @williamstarkro though!
