### ISSUE TITLE
Tooltips copies on Leaderboard page

### ISSUE THREAD

**Issue by mateodaza** [vacekj/regenscore#29]

**Comment by YineisyM** [comment]
Texts for this section. It would be ideal if the examples could be considered as part of the final text.

- ***Utilization:*** **Measure of user activity on the network.** Including transactions, contract interactions and deployment…
- ***Security:*** **Measure of user contribution to network security.** Including holding tokens, providing liquidity…
- **Governance:** **Measure of user participation in community governance**. Including voting, submitting proposals…
- ***Contribution:*** **Measure of user contribution to community development.** Including payment from treasury, holding contributor POAPs…
- ***Outreach:*** **Measure of user efforts to promote the community.** Including donations to public goods, participation in Regen project governance…

**Comment by mateodaza** [comment]
@YineisyM we also need to do Behavior and Points earned, look at the table!

<img width="1362" alt="image" src="https://github.com/vacekj/regenscore/assets/18689480/dd8063f4-5495-417c-af7e-d3b206649416">

**Comment by YineisyM** [comment]
Here's the description of each one @mateodaza 

- **Attestations:** Detailed list of attestations earned by each user. The attestations are classified by: utilization, security, governance, contribution, and outreach.
- **Network:** The network where the activity took place.
- **Behavior:** A concise description of the activity that resulted in the attestation
- **Value:** The number of tokens required or the attestation confirmation status.
- **Points earned:** The number of points awarded for the activity. These points are used to calculate the user's Regen Score.
