### ISSUE TITLE
Missing behaviours (Praise, TS attestation)

### ISSUE THREAD

**Issue by MaxSemenchuk** [vacekj/regenscore#44]
Status https://docs.google.com/spreadsheets/d/1YWaWZ6JKeZeLTA8-1aebbB8NJXOEYKjwEtFL9Dk99QI/edit#gid=0

Milestone new behaviours:
- [ ] Praise (from backend for now)
- [ ] Charity NFTs (from our [list](https://docs.google.com/spreadsheets/d/1YWaWZ6JKeZeLTA8-1aebbB8NJXOEYKjwEtFL9Dk99QI/edit#gid=0))

Next milestone:
- [ ] [OP Citizen House Badgeholder](https://optimism.easscan.org/schema/view/0xfdcfdad2dbe7489e0ce56b260348b7f14e8365a8a325aef9834818c00d46b31b)
- [ ] [OP Snapshot Voting](https://snapshot.org/#/opcollective.eth)
- [ ] [OP Agora Voting](https://optimistic.etherscan.io/address/0xcdf27f107725988f2261ce2256bdfcde8b382b10)

**Comment by mateodaza** [comment]
**Doing for next milestone**

- [ ]  On the $OP Treasury Multi-Sig
- [ ] Providing liquidity to the $OP/$WETH Pool
- [ ] Giveth Project owner
- [ ] Giveth Donations
- [ ] Trusted Seed Member

**Needs clarification**
- [ ] Charity NFTs Donations (Which ones?)
- [ ] OP Airdrop Handling (we're currently adding the score for airdrop receivers without more logic, should we increase complexity for launch?)

**Blocked** (I need the list or a source)
- [ ] Trusted seed skill tag ( I'm not sure what this is, is it a list? )
- [ ] OP Citizen House Badgeholder 
- [ ] OP Snapshot Voting
- [ ] OP Agora Voting


@MaxSemenchuk @vacekj

**Comment by GriffGreen** [comment]
OP Citizen House Badgeholder
- https://optimism.easscan.org/schema/view/0xfdcfdad2dbe7489e0ce56b260348b7f14e8365a8a325aef9834818c00d46b31b
There should be more coming soon... this is a list of the people who voted in RetroPGF 2... the badgeholders for RetroPGF might have a different attestation.

OP Snapshot Voting
- https://snapshot.org/#/opcollective.eth you have to go into each vote and download the CSV for each proposal... not sure if Yine, Ivy, or Algene want to make a quick list for you... 

OP Agora Voting
- It looks like all votes went thru this contract: https://optimistic.etherscan.io/address/0xcdf27f107725988f2261ce2256bdfcde8b382b10 
calling the same method "Cast Vote With Reason"

**Comment by vacekj** [comment]
Just finished scraping the OP Snapshot voters, there was over 1 million votes cast by over 88 thousand different addresses - pretty impressive.

Next up is OP Agora voting - thank you @GriffGreen for finding the contract for this - I'll analyze it and extend our scraping infra to include it.
