### ISSUE TITLE
Profile page (+Share feature)

### ISSUE THREAD

**Issue by MaxSemenchuk** [vacekj/regenscore#45]
Process:
- on wallet connection, I'm transferred to https://regenscore.io/profile/0x...(my address)
- there's another button next to mint – share in twitter **(prob will make a design)**
- it create a tweet with the link and text: "check out my RegenScore and check out yours"
- preview to the link shows a picture meter with latest score and address **(prob will make a design)**

**Comment by MaxSemenchuk** [comment]
process:
on wallet connection, i'm transferred to https://regenscore.io/profile/0x...(my address)

**Comment by vacekj** [comment]
https://github.com/vacekj/regenscore/issues/1 for a possible library to use for this @mateodaza @b3nik

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/5dFNktbUXFflLhYLu7gGkc/Regen-Score?type=design&node-id=1110%3A2603&mode=design&t=25Pcwd2AmKmbaUnZ-1

https://www.figma.com/file/5dFNktbUXFflLhYLu7gGkc/Regen-Score?type=design&node-id=1110%3A2755&mode=design&t=25Pcwd2AmKmbaUnZ-1

Links to the Share modal and Open graph Image for twitter
@MaxSemenchuk
