### ISSUE TITLE
Score loading

### ISSUE THREAD

**Issue by MaxSemenchuk** [vacekj/regenscore#46]

**Comment by vacekj** [comment]
@MaxSemenchuk 
1. the current designs for score loading are redundant, as we only have one step - loading score.
2. the tooltip to not close the page at the bottom is also unnecessary, as the user **can** close it, nothing bad will happen, we fetch the score in the background.
3. we don't require any action from the user to fetch the score currently, so should we opt for a less intrusive dialog?
