### ISSUE TITLE
secret scanner

### ISSUE THREAD

**Issue by MaxSemenchuk** [vacekj/regenscore#55]

**Comment by mateodaza** [comment]
This is for not pushing secret variables to the repo right? @MaxSemenchuk

**Comment by MaxSemenchuk** [comment]
@vacekj knows better, but it's not for Milestone 5 release

**Comment by vacekj** [comment]
A generalized secret scanner is in order here

**Comment by vacekj** [comment]
Enabled GitHub secret scanning that prevents commits containing secrets from being pushed to the repo.
